customCommands:
  - key: "<c-g>"
    context: "global"
    description: "AI Commit Message"
    loadingText: "Generating commit message"
    prompts:
      - type: "menu"
        title: "AI Commit Options"
        key: "action"
        options:
          - name: "Generate"
            description: "Generate new commit message"
            value: "generate"
          - name: "Commit"
            description: "Use current message"
            value: "commit"
          - name: "View"
            description: "View current message"
            value: "view"
          - name: "Clear"
            description: "Remove current message"
            value: "clear"
    command: |
      {{if eq .Form.action "generate"}}
        gen-commit-lazygit | tee /tmp/lazygit-commit-msg
      {{else if eq .Form.action "view"}}
        test -f /tmp/lazygit-commit-msg && cat /tmp/lazygit-commit-msg || echo "No commit message generated yet"
      {{else if eq .Form.action "clear"}}
        test -f /tmp/lazygit-commit-msg && rm /tmp/lazygit-commit-msg || echo "No commit message file exists"
      {{else}}
        git commit -m "$(cat /tmp/lazygit-commit-msg)" && rm /tmp/lazygit-commit-msg
      {{end}}
    output: popup
  - key: "<c-N>"
    context: "global"
    description: "Refine commit message"
    prompts:
      - type: "input"
        title: "Enter feedback for refinement"
        key: "feedback"
    command: 'cat /tmp/lazygit-commit-msg | mods -q -C "feedback: {{.Form.feedback}}"'
    output: popup
# Config relating to things outside of Lazygit like how files are opened, copying to clipboard, etc
os:
  # Command for editing a file. Should contain "{{filename}}".
  edit: ""

  # Command for editing a file at a given line number. Should contain
  # "{{filename}}", and may optionally contain "{{line}}".
  editAtLine: ""

  # Same as EditAtLine, except that the command needs to wait until the
  # window is closed.
  editAtLineAndWait: ""

  # Whether lazygit suspends until an edit process returns
  editInTerminal: false

  # For opening a directory in an editor
  openDirInEditor: ""

  # A built-in preset that sets all of the above settings. Supported presets
  # are defined in the getPreset function in editor_presets.go.
  editPreset: ""

  # Command for opening a file, as if the file is double-clicked. Should
  # contain "{{filename}}", but doesn't support "{{line}}".
  open: ""

  # Command for opening a link. Should contain "{{link}}".
  openLink: ""

  # CopyToClipboardCmd is the command for copying to clipboard.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-command-for-copying-to-and-pasting-from-clipboard
  copyToClipboardCmd: printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty 
  # ReadFromClipboardCmd is the command for reading the clipboard.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-command-for-copying-to-and-pasting-from-clipboard
  readFromClipboardCmd: ""

  # A shell startup file containing shell aliases or shell functions. This will be sourced before running any shell commands, so that shell functions are available in the `:` command prompt or even in custom commands.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#using-aliases-or-functions-in-shell-commands
  shellFunctionsFile: ""
